networks:
  backnet:
  frontnet:

services:

  # This is the proxy which receives all http requests and forwards to relevant servers.
  proxy:
    image: caddy:latest
    container_name: proxy-caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - frontnet
      - backnet
    depends_on:
      - webserver
    volumes:
      - ./web/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web/certificates/localhost.crt:/etc/caddy/cert.crt:ro # replace with real certificate
      - ./web/certificates/localhost.key:/etc/caddy/key.key:ro # replace with real key
    restart: unless-stopped

  # Web server hosts the static files
  webserver:
    platform: linux/amd64
    image: ${WEB_IMAGE} # Docker will use the images defined in .env
    expose:
      - 8080:8080
    networks:
      - backnet
    restart: unless-stopped

  # API server runs the rails project
  apiserver:
    platform: linux/amd64
    image: ${API_IMAGE}
    env_file:
      - ./api/.env.production
    ports:
      - 3000:3000
    networks:
      - backnet
    depends_on:
      - ontrack-db
    volumes:
      - student_work:/student-work # Adjust path to where student data should be stored
      - ./api/logs:/doubtfire/log
      - ./api/shared-files:/shared-files
      - ./api/shared-files/aliases:/etc/aliases:ro
      - ./api/database.yml:/doubtfire/config/database.yml:ro
      - ./api/custom_institution_setting.rb:/doubtfire/config/custom_institution_setting.rb:ro
      - ./api/secrets:/doubtfire/config/credentials:ro
    environment:
      - TZ=Australia/Melbourne
    command: /bin/bash -c "bundle exec rails s -b 0.0.0.0"
    restart: on-failure:5

  # Secondary api image used for zero down-time deployment.
  apiserver-green:
    platform: linux/amd64
    image: ${API_IMAGE_GREEN}
    env_file:
      - ./api/.env.production
    ports:
      - 3002:3000
    networks:
      - frontnet
    depends_on:
      - redis-sidekiq
    volumes:
      - student_work:/student-work
      - ./api/logs:/doubtfire/log
      - ./api/shared-files:/shared-files
      - ./api/shared-files/aliases:/etc/aliases:ro
      - ./api/database.yml:/doubtfire/config/database.yml:ro
      - ./api/custom_institution_setting.rb:/doubtfire/config/custom_institution_setting.rb:ro
      - ./api/secrets:/doubtfire/config/credentials:ro
    environment:
      - TZ=Australia/Melbourne
    command: /bin/bash -c "bundle exec rails s -b 0.0.0.0"
    restart: unless-stopped

  # Database server - could be external to docker
  ontrack-db:
    image: mariadb:10
    restart: always
    networks:
      - backnet
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: dfire # Update with mariadb username
      MARIADB_PASSWORD: pwd # Update with mariadb password
      MARIADB_DATABASE: doubtfire # Update with mariadb database name
    volumes:
      - mysql_db:/var/lib/mysql

  # Automated generation of PDFs using cron
  pdfgen:
    platform: linux/amd64
    image: ${API_IMAGE}
    env_file:
      - ./api/.env.production
    networks:
      - backnet
    depends_on:
      - ontrack-db
    volumes:
      - student_work:/student-work # Update with path to student work
      - ./api/shared-files:/shared-files
      - ./api/shared-files/aliases:/etc/aliases:ro
      - ./api/logs:/doubtfire/log
      - ./api/tmp/latex-pdfgen:/doubtfire/tmp/rails-latex
      - ./api/database.yml:/doubtfire/config/database.yml:ro
      - ./api/custom_institution_setting.rb:/doubtfire/config/custom_institution_setting.rb:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - jplag_tmp:/doubtfire/tmp/jplag # jplag - api will extract to root/tmp/jplag
      - ./api/secrets:/doubtfire/config/credentials:ro
    environment:
      - TZ=Australia/Melbourne
      - LATEX_CONTAINER_NAME=texlive-container-pdfgen
    command: /doubtfire/lib/shell/pdfgen_entry_point.sh
    restart: on-failure:5

  redis-sidekiq:
    container_name: redis-sidekiq
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - backnet
    environment:
      - TZ=Australia/Melbourne
    expose:
      - 6379
    restart: unless-stopped


  sidekiq:
    platform: linux/amd64
    image: ${API_IMAGE}
    env_file:
      - ./api/.env.production
    networks:
      - backnet
    depends_on:
      - ontrack-db
      - redis-sidekiq
    volumes:
      - student_work:/student-work # Update with path to student work
      - ./api/shared-files:/shared-files
      - ./api/shared-files/aliases:/etc/aliases:ro
      - ./api/logs:/doubtfire/log
      - ./api/tmp/latex-sidekiq:/doubtfire/tmp/rails-latex
      - ./api/database.yml:/doubtfire/config/database.yml:ro
      - ./api/custom_institution_setting.rb:/doubtfire/config/custom_institution_setting.rb:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/tmp/overseer:/doubtfire/tmp/overseer
      - ./api/secrets:/doubtfire/config/credentials:ro
    environment:
      DOCKER_HOST: host.docker.internal
      LATEX_CONTAINER_NAME: texlive-container
    command: /doubtfire/lib/shell/sidekiq_entry_point.sh
    restart: on-failure:5

  # LaTeX container dedicated to to the Sidekiq Task PDF gen queue
  texlive:
    container_name: texlive-container
    image: ${TEXLIVE_IMAGE}
    volumes:
      - student_work:/student-work
      - ./api/tmp/latex-sidekiq:/workdir/texlive-latex
    command: /bin/sh -c "luaotfload-tool --update --force && sleep infinity"
    restart: unless-stopped

  # LaTeX container dedicated to compiling portfolios only
  texlive-pdfgen:
    container_name: texlive-container-pdfgen
    image: ${TEXLIVE_IMAGE}
    volumes:
      - student_work:/student-work
      - ./api/tmp/latex-pdfgen:/workdir/texlive-latex
    environment:
      - TZ=Australia/Melbourne
    command: /bin/sh -c "luaotfload-tool --update --force && sleep infinity"
    restart: unless-stopped

  jplag:
    container_name: jplag
    image: ${JPLAG_IMAGE}
    volumes:
      - student_work:/student-work # where results are returned
      - jplag_tmp:/tmp/jplag # files shared with api container
    environment:
      - TZ=Australia/Melbourne
    command: /bin/sh -c "sleep infinity"
    restart: unless-stopped
    network_mode: none

  lti:
    image: ${LTI_IMAGE}
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - frontnet
    env_file:
      - ./.env.lti.production
    environment:
      HOST: apiserver

  mongodb:
    image: mongo:7
    restart: unless-stopped
    container_name: lti-mongodb
    ports:
      - "27017:27017"
    networks:
      - frontnet
    env_file:
      - ./api/.env.production
    volumes:
      - mongo_data:/data/db

volumes:
  latex_tmp: {}
  redis_data: {}
  doubtfire_logs: {}
  mysql_db: {}
  student_work: {}
  jplag_tmp: {}
