version: '3.8'

networks:
  backnet:
  frontnet:

services:

  # This is the proxy which receives all http requests and forwards to relevant servers.
  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - webserver
      - apiserver
    networks:
      - frontnet
      - backnet
    volumes:
      - ./shared-files/proxy-nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.crt:/etc/nginx/cert.crt # replace with real certificate
      - ./localhost.key:/etc/nginx/key.key # replace with real key
    restart: on-failure:5

  # Web server hosts the static files
  webserver:
    platform: linux/amd64
    image: lmsdoubtfire/doubtfire-web:10.0.0-2
    # ports:
    #   - 8080:8080
    networks:
      - backnet
    restart: on-failure:5

  # API server runs the rails project
  apiserver:
    platform: linux/amd64
    image: lmsdoubtfire/apiserver:10.0.0-2
    env_file:
      - .env.production
    # ports:
    #   - 3000:3000
    networks:
      - backnet
    depends_on:
      - doubtfire-db
    volumes:
      - student_work:/student-work # Adjust path to where student data should be stored
      - doubtfire_logs:/doubtfire/log
      - ./shared-files:/shared-files
      - ./shared-files/aliases:/etc/aliases:ro
    command: /bin/bash -c "bundle exec rails s -b 0.0.0.0"
    restart: on-failure:5

  # Database server - could be external to docker
  doubtfire-db:
    image: mariadb:10
    restart: always
    networks:
      - backnet
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: dfire # Update with mariadb username
      MARIADB_PASSWORD: pwd # Update with mariadb password
      MARIADB_DATABASE: doubtfire # Update with mariadb database name
    volumes:
      - mysql_db:/var/lib/mysql

  # Automated generation of PDFs using cron
  pdfgen:
    platform: linux/amd64
    image: lmsdoubtfire/appserver:10.0.0-2
    env_file:
      - .env.production
    networks:
      - backnet
    depends_on:
      - doubtfire-db
    volumes:
      - student_work:/student-work # Update with path to student work
      - ./shared-files:/shared-files
      - ./shared-files/aliases:/etc/aliases:ro
      - doubtfire_logs:/doubtfire/log
      - latex_tmp:/doubtfire/tmp/rails-latex
    command: /doubtfire/lib/shell/pdfgen_entry_point.sh
    restart: on-failure:5

  redis-sidekiq:
    container_name: redis-sidekiq
    image: redis:7.0
    volumes:
      - redis_data:/data
    networks:
      - backnet

  sidekiq:
    platform: linux/amd64
    image: lmsdoubtfire/appserver:10.0.0-2
    env_file:
      - .env.production
    environment:
      DOCKER_HOST: host.docker.internal
    networks:
      - backnet
      - frontnet
    depends_on:
      - doubtfire-db
      - redis-sidekiq
    volumes:
      - student_work:/student-work # Update with path to student work
      - ./shared-files:/shared-files
      - ./shared-files/aliases:/etc/aliases:ro
      - doubtfire_logs:/doubtfire/log
      - latex_tmp:/doubtfire/tmp/rails-latex
    command: /doubtfire/lib/shell/sidekiq_entry_point.sh
    restart: on-failure:5

  texlive:
    container_name: texlive-container
    image: lmsdoubtfire/formatif-latex:10.0.0-3
    # build:
    #   context: ../
    #   dockerfile: texlive.Dockerfile
    volumes:
      - student_work:/student-work
      - latex_tmp:/workdir/texlive-latex
    command: /bin/sh -c "sleep infinity"

volumes:
  latex_tmp: {}
  redis_data: {}
  doubtfire_logs: {}
  mysql_db: {}
  student_work: {}

