version: '3'

networks:
  frontnet:
  backnet:
    internal: true

services:
  formatif-dev-container:
    container_name: 1-formatif-dev-container
    image: lmsdoubtfire/formatif-devcontainer:10.0.0-5
    # build:
    #   context: ../
    #   dockerfile: dev.Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached
      - formatif_tmp_compose:/workspace/tmp
      - student-work:/student-work
      - jplag_results:/jplag_results
      - ws_node_modules:/workspace/node_modules
      - web_node_modules:/workspace/doubtfire-web/node_modules
      - formatif_gems_compose:/home/vscode/.gems
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontnet
      - backnet
    ports:
      - "9876:9876"
      - "4200:4200"
      - "3000:3000"
    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 5000; do :; done"
    env_file:
      - devcontainer.env
    environment:
      LATEX_CONTAINER_NAME: 1-formatif-texlive-container
      LATEX_BUILD_PATH: /texlive/shell/latex_build.sh
    depends_on:
      - dev-db
      - ./devcontainer.env

  # JPlag
  jplag:
    container_name: jplag
    build:
      context: ../jplag
      dockerfile: jplag.Dockerfile
    volumes:
      - student-work:/student-work
      - jplag_data:/jplag
      - jplag_results:/jplag/results
      - ../doubtfire-api/tmp/jplag:/tmp/jplag
    command: /bin/sh -c "sleep infinity"
    env_file:
      - ./devcontainer.env

  dev-db:
    container_name: doubtfire-dev-db
    image: mariadb:10
    restart: always
    volumes:
      # - ./:/workspace/.devcontainer/
      - formatif_db_compose:/var/lib/mysql
    env_file:
      - devcontainer.env
    networks:
      - backnet

  redis-sidekiq:
    container_name: doubtfire-redis-sidekiq
    image: redis:7.0
    volumes:
      - formatif_redis_sidekiq_data:/data
    networks:
      - backnet

  texlive:
    container_name: 1-formatif-texlive-container
    image: lmsdoubtfire/formatif-latex:10.0.0-2
    # build:
    #   context: ../
    #   dockerfile: texlive.Dockerfile
    volumes:
      - formatif_student-work_compose:/student-work
      - ../doubtfire-api/tmp/rails-latex:/workdir/texlive-latex
      - ../doubtfire-api/public/assets/images:/workspace/doubtfire-api/public/assets/images
      - ../doubtfire-api/test_files:/workspace/doubtfire-api/test_files
    depends_on:
      - formatif-dev-container
    command: /bin/sh -c "sleep infinity"

volumes:
  ws_node_modules:
  web_node_modules:
  formatif_tmp_compose:
  student-work: {}
  formatif_db_compose:
  formatif_gems_compose:
  formatif_redis_sidekiq_data:
  jplag_data:
  jplag_results:
