services:

  formatif-dev-container:
    container_name: formatif-dev-container
    image: lmsdoubtfire/formatif-devcontainer:8.3-dev
    build:
      context: ../
      dockerfile: dev.Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached
      - formatif_tmp_compose:/workspace/tmp
      - student-work:/student-work
      - ws_node_modules:/workspace/node_modules
      - web_node_modules:/workspace/doubtfire-web/node_modules
      - formatif_db_compose:/var/lib/mysql
      - formatif_gems_compose:/home/vscode/.gems
    ports:
      - "9876:9876"
      - "4200:4200"
      - "3000:3000"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 5000; do :; done"
    env_file:
      - ./devcontainer.env

  # This is the proxy which receives all http requests and forwards to relevant servers.
  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    expose:
      - 80:80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy-nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure:2
    env_file:
      - ./devcontainer.env

volumes:
  ws_node_modules:
  web_node_modules:
  formatif_tmp_compose:
  student-work: {}
  formatif_db_compose:
  formatif_gems_compose:
